### ISSUE TITLE
Use OptimalControlProblems

### ISSUE THREAD

**Issue by ocots** [0Yassine0/COTS.jl#28]
Replace the problems for the tests and benchmarking by the problems from `OptimalControlProblems.jl`. Since, the repo is not a registered package, the location needs to be given in the `Project.toml` with the keyword `where`. See: https://github.com/JuliaLang/Pkg.jl/issues/492.

**Comment by 0Yassine0** [comment]
@ocots  @jbcaillau 

The problems of `OptimalControlProblems.jl` are `NLPModels` and only resolvable with `sol_nlp = NLPModelsIpopt.ipopt()`.

To plot the solution we usually use `OptimalControl.plot()`  but it only takes `OptimalControlSolution` as an argument.

And the only way I found to obtain an `OptimalControlSolution` is by using `sol = OptimalControlSolution(docp; primal=sol_nlp .solution, dual=sol_nlp .multipliers)` which we can't use here because we don't have the `docp`.

Is there another way to plot the solution or should we change what `OptimalControlProblems.jl` functions return.

**Comment by frapac** [comment]
You can access the object `docp`, it's one of the attribute in `nlp` as far as I recall. I guess `nlp.docp`?

**Comment by 0Yassine0** [comment]
> You can access the object `docp`, it's one of the attribute in `nlp` as far as I recall. I guess `nlp.docp`?

I can't find it in the [Attributes](https://jso.dev/NLPModels.jl/stable/#Attributes) of NLPModels.

I guess the DOCP only defined inside `OptimalControl` [here](https://github.com/control-toolbox/CTDirect.jl/blob/21c18e99494e7a967d2f74256f88c6b16ad36d2c/src/problem.jl#L21) and it requires the OCP and other data.

**Comment by ocots** [comment]
We have removed `docp` from `nlp`. Could we return the `nlp` and the `docp` in OptimalControlProblems.jl?

**Comment by 0Yassine0** [comment]
> We have removed `docp` from `nlp` I think. Could we return the `nlp` and the `docp` in OptimalControlProblems.jl?

Yes, that'll be easier to change.

**Comment by jbcaillau** [comment]
@0Yassine0 good
- to plot, check the end of this paragraph https://control-toolbox.org/OptimalControl.jl/stable/tutorial-nlp.html#Resolution-of-the-NLP-problem
- MadNLP is also supported 🙂 https://control-toolbox.org/OptimalControl.jl/stable/tutorial-nlp.html#Change-the-NLP-solver

**Comment by 0Yassine0** [comment]
Done
